### ISSUE TITLE
Core-scroll does not always disable control buttons

### ISSUE THREAD

**Issue by janerikbr** [nrkno/core-components#140]
On Chrome 70 on Windows 10, if core-scroll is set up to control buttons by using the `data-core-scroll="my-scroll-js"`, the left scroll button doesn't seem to get the `disabled` attribute even though there are no more pixels to the left. This seems to happen on larger screen widths only.

Can be seen on https://tv.nrk.no.

Works fine in other browsers, and on Chrome for Mac.

**Comment by eirikbacker** [comment]
Can not reproduce for now
