### ISSUE TITLE
Core-progress with value 0

### ISSUE THREAD

**Issue by christianeide** [nrkno/core-components#173]
Hi,

I cant seem to set the value of the progress bar to 0. The value/state updates, but the progressbar do not update. Is this expected behaviour? If I set the value to 0.1 it works

using the JSX-version

`"@nrk/core-progress": "1.0.2"`

**Comment by laat** [comment]
I'm guessing this line is the culprit.
https://github.com/nrkno/core-components/blob/c9b200268a3a4aed719e3d471d74e033b32bf3b6/packages/core-progress/core-progress.js#L19

If that is so, I believe setting value to the string "0" should work.
```js
<CoreProgress value="0" max={100} />
```

**Comment by laat** [comment]
should work in the latest release
