### ISSUE TITLE
Dialog warning

### ISSUE THREAD

**Issue by KristoferMyhre** [nrkno/core-components#219]
Hello,

Our team are using your dialog component, and we have a minor issue. When sending a boolean attribute to the "modal" prop, we get a warning telling us it wants a string instead.

It looks like it is working properly, so the only issue is getting a warning that shouldn't be there.

Is this correct? Or are we missing something? We added some images to show you our problem.
 
<img width="697" alt="Skjermbilde 2019-04-04 kl  10 04 26" src="https://user-images.githubusercontent.com/2319231/55539693-8b76b400-56c1-11e9-8b93-3b72beefb5c7.png">
<img width="879" alt="Skjermbilde 2019-04-04 kl  10 05 09" src="https://user-images.githubusercontent.com/2319231/55539695-8dd90e00-56c1-11e9-9b3d-9f7fae5d9270.png">

**Comment by eirikbacker** [comment]
Hi Kristofer! Thanks for heads up,! I presume you are you using the JSX version? :)

**Comment by KristoferMyhre** [comment]
Supert! Takk for kjapp tilbakemelding og fiks!
