### ISSUE TITLE
core-dialog: A dialog in a dialog makes it impossible to open the first dialog

### ISSUE THREAD

**Issue by esseb** [nrkno/core-components#232]
Testcase: https://codesandbox.io/s/6wv94vw92z

Opening dialog one immediately triggers dialog two's `onClose` callback which triggers dialog one's `onClose` callback, plus a few more `onClose` callbacks in addition. The result is that it's impossible to open dialog one.

I could solve this problem by e.g. rendering the two dialogs as siblings within the same parent, but that's not ideal.

Using `ReactDOM.createPortal()` as a workaround doesn't work: https://codesandbox.io/s/ox1j4k77oq

**Comment by eirikbacker** [comment]
that's impossible CSS wize, when needing to toggle between - why nest inside one another, or can you just close the upper one? :)

**Comment by esseb** [comment]
What do you mean with "toggle between"?

**Comment by eirikbacker** [comment]
I guess I need dialogs inside of each other, and if I understand you use case, you
1) open outer dialog
2) open inner dialog
3) want to bring forward outer dialog (but this does not work as it is the parent of inner dialog)

So, visually you try toggle between the different dialogs? Nesting is not possible if you need to toggle between :)

**Comment by esseb** [comment]
No, I only need 1 and 2.

**Comment by eirikbacker** [comment]
ah, confused by the issue title 😅 well, this will also be resolved by #169 :D

**Comment by esseb** [comment]
Excellent.
