### ISSUE TITLE
core-scroll: Scroll sticks when mouse is released outside document

### ISSUE THREAD

**Issue by simenbrekken** [nrkno/core-components#239]
core-scroll [currently attaches listeners to `document`](https://github.com/nrkno/core-components/blob/master/packages/core-scroll/core-scroll.js#L55-L56). When initiating a scroll via `mousedown` and then releasing the mouse button outside the current document the `mouseup` handler is not triggered:

![core-scroll-sticky-outside-document](https://user-images.githubusercontent.com/12807/57511930-a6fd5c00-730a-11e9-8752-97e6d06d0523.gif)

I'm not sure if this is intentional but a possible fix would be attaching `mouseup` to `window` while retaining `mousemove` on document to prevent this.

**Comment by eirikbacker** [comment]
Thanks for heads up! will look into this in #169

**Comment by htor** [comment]
hmm, can't reproduce this with core-scroll@3.1.2. vanilla or react version.
what version are you using?

**Comment by simenbrekken** [comment]
@htor We're using 3.1.2 React for our [ScrollContainer](https://github.com/nrkno/PS.Web/blob/master/NrkTvPages/src/components/ScrollContainer/ScrollContainer.tsx)

**Comment by htor** [comment]
@simenbrekken are you able to reproduce this with the latest major version (v4)? we just did a major rewrite using custom elements, that might have fixed the issue.

**Comment by simenbrekken** [comment]
@htor I'll try to get around to this next week.

**Comment by eirikbacker** [comment]
Any news on this @simenbrekken ? :)

**Comment by simenbrekken** [comment]
@eirikbacker I did not in fact get around to this I'm afraid, but it's on my (long) todo list.

**Comment by simenbrekken** [comment]
I'm unable to reproduce this either in the previous or the current version. I'll reopen this if it shows up again.

**Comment by simenbrekken** [comment]
I'm currently in the process of upgrading NrkTvPages to use core-scroll ^4.0.4 and the sticky behavior has resurfaced with this.

[Screen Recording 2019-06-21 at 13.41.11.zip](https://github.com/nrkno/core-components/files/3314303/Screen.Recording.2019-06-21.at.13.41.11.zip)

In the video I first do some regular drag and drop scrolling before grabbing, moving the cursor outside the current `document` and releasing it. After that the cursor sticks to my pointer as no release event has been triggered.

**Comment by eirikbacker** [comment]
Thanks for screen recording :) this is chrome, with responsive device mode enabled?
I'll gladly pop by Monday and have a look - struggling to reproduce here

**Comment by eirikbacker** [comment]
Only happens in iframes, hard to fix :(
