### ISSUE TITLE
core-suggest: highlight optional

### ISSUE THREAD

**Issue by htor** [nrkno/core-components#243]
with larger number of list items, the highlight algo gets slow. 
perhaps write a couple of unit tests and enhance step by step?

**Comment by wwalmnes** [comment]
After discussing with Eirik, I was informed that the performance seems to degrade when the list is about 2000 items large. I'm curious as to why someone would want to display that many items? Perhaps recommend in the documentation that one should limit the amount of items displayed?

**Comment by eirikbacker** [comment]
Renamed the issue to making highlight optional - we should let the user send the attribute `hightlight="off"` (matching the semantics of https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) to disable highlight functionality

**Comment by eirikbacker** [comment]
Lets fix #373 in this issue as well - I suggest disabling highlight automatically when using IE11 as this browser does not handle it well anyway and its more nice-to-have than needed :)
