### ISSUE TITLE
core-dialog: All dialogs close when closing nested dialog

### ISSUE THREAD

**Issue by esseb** [nrkno/core-components#247]
Testcase: https://codesandbox.io/s/nrknocoredialog-closing-nested-dialog-bug-ivnrp

Closing dialog two closes dialog one also because both dialogs' `onDialogToggle` callback functions are called.

**Comment by htor** [comment]
thanks for the detailed issue! looking into it

**Comment by htor** [comment]
fixed in https://github.com/nrkno/core-components/pull/249

**Comment by htor** [comment]
@esseb just install `@nrk/core-dialog@2.0.1` and it should work

**Comment by esseb** [comment]
Thanks, @htor, `2.0.1` works great.
