### ISSUE TITLE
core-dialog: Unique tag name triggers React hydration warning

### ISSUE THREAD

**Issue by esseb** [nrkno/core-components#256]
I get this warning when using `@nrk/core-dialog@2.0.3` in `react16.8.6` in dev mode:
> react-dom.development.js:506 Warning: Expected server HTML to contain a matching &lt;coredialog-jw688k8f156&gt; in &lt;div&gt;.

The [React documentation about hydration](https://reactjs.org/docs/react-dom.html#hydrate) says that "you should treat mismatches as bugs and fix them"

As far as I can tell from the [source](https://github.com/nrkno/core-components/blob/master/packages/utils.js#L99) this is because the element's tag name is a generated UUID based on the current time, which will naturally differ between server and client.

Is there an option I can use to ensure this unique tag name is identical between the server and the client? The generic tag name `core-dialog` with no UUID would be enough for my purposes so I would be fine with a solution where I could disable the unique tag.

**Comment by eirikbacker** [comment]
Not good enough for other users, but we can solve this with version-number instead :) @htor

**Comment by esseb** [comment]
Something like a version number would be fine :)

**Comment by htor** [comment]
@esseb can you confirm this works in latest `master`? thanks

**Comment by esseb** [comment]
@htor latest master (`3b864c8`) looks fine.

The custom element is now rendered with the tag name `core-dialog-react` on both server and client. No warning from React (other than https://github.com/nrkno/core-components/issues/261 which is unrelated).

Closing.
