### ISSUE TITLE
core-dialog: backdrop not created when using React version

### ISSUE THREAD

**Issue by esseb** [nrkno/core-components#257]
Testcase: https://codesandbox.io/s/nrknocoredialog-backdrop-element-not-created-8w4k9

Using @nrk/core-dialog@2.0.3 and react@16.8.6

I've only tested the React version so I'm not sure if this bug is unique to the React version of core-dialog.

The backdrop does get created if you click anywhere in the viewport after opening the dialog, or if you access the `coreDialogElement.backdrop` getter.

**Comment by eirikbacker** [comment]
Hi! this is because you re-render the whole dialog, instead of toggelig the `hidden` attribute.
Doing this instead fixes it:
```
<CoreDialog
        hidden={!showDialog} 
```
ofc, we should also ensure removing the whole dom works @htor  :)

**Comment by esseb** [comment]
I'm intentionally not using the `hidden` attribute. Is that a requirement?

**Comment by esseb** [comment]
I'm not sure what you mean by "re-render" or "removing the whole dom", I'm only rendering the dialog once in that testcase and never removing it.

**Comment by eirikbacker** [comment]
Closed by #259
