### ISSUE TITLE
core-scroll: Nudges scroll on release

### ISSUE THREAD

**Issue by simenbrekken** [nrkno/core-components#285]
Sometimes when the cursor is pressed and released on an element inside a `core-scroll` container it's nudged and animated ~10px.

![core-scroll-nudge-nudge-know-what-i-mean](https://user-images.githubusercontent.com/12807/60095923-00510b80-9750-11e9-9c2e-a7dd8cd61e89.gif)

**Comment by eirikbacker** [comment]
Momentum a bit too sensitive

**Comment by eirikbacker** [comment]
Will be resolved by #289
