### ISSUE TITLE
core-dialog: consider aria-hidden on other content

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-components#296]
- Very few browsers respect `role="dialog"`, so screen readers can navigate outside
- User testing showed this is not a big deal as users do not expect dialog behaviour online
- Still, we could still try to fix this by setting `aria-hidden` on external content
- Want input on this one @kristofferlium :)

**Comment by htor** [comment]
after speaking with @kristofferlium we have decided to do perf tests using kurator-front-office (mocked version) with different dialog + toggling strategies. will update this thread with test results

**Comment by htor** [comment]
did some tests with @kristofferlium and it seems screen readers will get unresponsive or very slow when dealing with many aria-hidden states to toggle between.

leaving test code here for reference:
[aria-hidden-dialog-test.zip](https://github.com/nrkno/core-components/files/3727671/aria-hidden-dialog-test.zip)
