### ISSUE TITLE
Cross browser integration testing with BrowserStack

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-components#300]
To ensure all functionality works as intended in all browsers.

**Comment by htor** [comment]
yes. this means we have to do another re-write of all tests now using selenium (and nighwatch?).

**Comment by eirikbacker** [comment]
yupp, seems like it :/ thought selenium could run with several drivers, but nah. core-components is most relevant in the first place for such a transition, but probably other projects as well.

**Comment by htor** [comment]
after doing some research, it looks like protractor is a good driver candidate. i'll write a couple of tests and see how that works.

**Comment by eirikbacker** [comment]
Maybe use the list Ludo uses in the first place? :)
