### ISSUE TITLE
core-datepicker jsx: does not used passed month /day names as expected

### ISSUE THREAD

**Issue by piofinn** [nrkno/core-components#314]
When passed custom month or day names, the component does not use them as expected: The month names are used to render the name above the calendar, but not in the dropdown menu (the `<select>` element). The day values are not used at all.

### 📋 Steps to reproduce

1. Go to http://fremtind.github.io/jokul/components/datepicker
2. Choose different months with the dropdown in the datepicker labeled "Example in English"
3. (optional) You can edit the values used, by expanding the "Kode" section beneath the example (the code shown is editable)

### ✅ Expected behavior

I expect the alternatives in the dropdown, and labeling the weekdays, to be the same as those supplied as an attribute to the CoreDatepicker component.

### ❌ Actual behavior

Both the month alternatives in the dropdown and the labels on the weekdays are the built-in standard Norwegian words. However, the month name shown above the calendar view is updated according to supplied values.

**Comment by laat** [comment]
Thanks, I verified the bug and attempted to fix it.

The maintainers are currently on vacation I believe.

**Comment by piofinn** [comment]
Well, that was quick! I tried to apply your changes locally, and it seems to fix it here at least ☺️

**Comment by eirikbacker** [comment]
Sorry about the delay @piofinn ! Some changes updated in branch now :)

**Comment by eirikbacker** [comment]
@piofinn https://www.npmjs.com/package/@nrk/core-datepicker 🎉 
Thanks for good reporting and follow up! 👍
