### ISSUE TITLE
Stepping by month or year with disabled dates makes month or year unable to access

### ISSUE THREAD

**Issue by peternic** [nrkno/core-components#319]
Hi, I am implementing your datepicker at Gjensidige, and we are using min and max dates with disabled dates.

So when for instance the selected date in the datepicker is 1st of May and the min date is set to 10th of April, then it is not allowed to choose April as a month, since selecting April would set the date to 1st og April and that is not allowed.
I found it confusing at the beginning not being able to choose April, and expected maybe the step back to april to select the first available date in April or something.

So I am just wondering if this is by design? Might just be me that find it confusing 😄 

I understand that it might be difficult to implement what I am saying due to the disabled 
function not only handles the simple min/max scenario.

Thanks for a great datepicker!

**Comment by eirikbacker** [comment]
Hi Peter!

Good point! A little unsure how your code looks - that might affect the month-picker.. Are you using <select> or <button> tags for this? Would be nice to see some sample code, but I have I hunch what causes the issue!

Currently cycling Denmark, but back for more support Monday! Very cool you use the datepicker, and much appreciate questions and feedback :)

**Comment by peternic** [comment]
Hi, thanks for fast response 👍 
Simplified I am doing like this, with react:
```
const disabledDates = (date: Date) => {
    const { min, max } = props;
    if (min && max) {
      return date < min || date > max;
    }
    if (min) {
      return date < min;
    }
    if (max) {
      return date > max;
    }
    return false;
  };

<CoreDatepicker
          id={props.id}
          timestamp={props.date.getTime()}
          onDatepickerChange={onChangeDate}
          disabled={disabledDates}>
          <div>
               <div>
                     <button value="-1 month">
                           <KeyboardArrowLeft />
                     </button>
                     <label>
                           {formatDate(props.date, 'MMMM)}
                     </label>
                     <button value="+1 month">
                          <KeyboardArrowRight />
                     </button>
               </div>
               <table>
          </div>
</CoreDatepicker>
```
My understanding is that the datepicker will evaluate the button value to a date and then disable the button if the date is a disabled date?

Maybe there are different ways of doing this 😃 

Thanks for any help! (Monday will be perfect, soon weekend)

**Comment by eirikbacker** [comment]
Hi again Peter! Thanks for good code example! I see - the `+1 month` ends up on a disabled date. We have actually encountered this once before - there is a difference between selected date, and visible month, but accessibility-wise this is not really considered by the current spec. NRKs best man on accessibility is currently away, but I'll send you a workaround today, and do a propper testing with @kristofferlium next week 👍

**Comment by eirikbacker** [comment]
Hi @peternic!
So I'll need to discuss a bit how we'll best navigate in disabled dates with my colleague. But in the meantime, you can use a custom function for month pagination, making sure the next/prev month is always kept within min/max-limits as such:
```
const disabledDates = (date: Date) => {
  const { min, max } = props
  return (min && date < min) || (max && date > max)
}

const paginateMonth = (step) => {
  const { min, max, date } = props
  const next = new Date(date).setMonth(date.getMonth() + step)
  return Math.max(min || 0, Math.min(max || Infinity, next))
}

<CoreDatepicker
  timestamp={this.state.date.getTime()}
  disabled={this.disabled}
  onDatepickerChange={this.onChange}>
   <button value={paginateMonth(-1)}>
     <KeyboardArrowLeft />
   </button>
   <label>
     {formatDate(props.date, 'MMMM)}
   </label>
   <button value={paginateMonth(+1)}>
     <KeyboardArrowRight />
   </button>
   <table />
</CoreDatepicker>
```
Hope that helps and thanks again for reporting :)

**Comment by peternic** [comment]
Thanks, thats is similar to what we are doing for now, only a little shorter and more concise so thanks 👍 

Thank you for helping out!

**Comment by markusv** [comment]
Any progress on this? I have the same problem

**Comment by eirikbacker** [comment]
Not a very simple fix, as this is raises a lot of accessibility concerns. Would recommend taking the dialog with @kristofferlium  :)

**Comment by skjalgepalg** [comment]
Closing this issue due to lack of further activity and likely relation/overlap with to https://github.com/nrkno/core-components/issues/386
