### ISSUE TITLE
core-dialog: From element not focused when closing dialog by removing dialog from the DOM

### ISSUE THREAD

**Issue by esseb** [nrkno/core-components#330]
See testcase at https://codesandbox.io/s/nrknocore-dialog-focus-after-unmounted-dzgjz

When closing dialogs I'd like to simply unmount it/remove it from the DOM since we can't just use the `hidden` property for various reasons.

When closing dialogs in this way the button that originally opened the dialog is not focused. The `onDialogToggle` callback does not get called either.

**Comment by eirikbacker** [comment]
If you remove the element altogether, we can provide a focus back to the button I guess, but calling `onDialogToggle` seems a bit weird? But as you are actually the one removing the element - you can also trigger functions you need? :)

**Comment by esseb** [comment]
Yeah, the event is not that useful in this case :)
