### ISSUE TITLE
core-dialog: focus not always restored correctly

### ISSUE THREAD

**Issue by janerikbr** [nrkno/core-components#333]
## Description
On the new nrk-tv series page, which can be seen [here](https://tv-preprod.nrk.no/serie/brennpunkt), we use `@nrk/core-dialog/jsx` to open an overlay whenever a user clicks a share button.

However, focus is not always restored correctly when user closes the dialog – sometimes it becomes `body`, and sometimes it becomes a button within the dialog itself (which is now in fact closed). This seems to be caused by the fact that core-dialog's `attributeChangeCallback` runs twice, also causing `from.focus()` to be called twice. Not sure why this happens though.

@simenbrekken and I was able to prevent the code within the `attributChangeCallback` from executing if the `hidden` attribute was not changed by inserting a circuit breaker:

```
const isMounted = attr === undefined;
const hasToggledHidden = attr === 'hidden' && prev !== next;

 if (!isMounted && !hasToggledHidden) {
    console.log('No change in hidden');
    return;
 }
```

**Comment by eirikbacker** [comment]
Thanks for heads up :) there is some logic that can cause "`hidden`" even if not actually togglig hidden (see https://github.com/nrkno/core-components/issues/330), so want to debug a bit more :)
