### ISSUE TITLE
core-dialog: JSX version fails to read backdrop attribute on mount

### ISSUE THREAD

**Issue by simenbrekken** [nrkno/core-components#344]
It seems `<CoreDialog backdrop="foo" />` fails to read the `backdrop` attribute on mount causing a separate `backdrop` element to be created:

Here's what happens when I render `<CoreDialog backdrop="foo" hidden />`:

```
attributeChangedCallback {attr: "hidden", prev: null, next: ""}
connectedCallback
attributeChangedCallback {attr: undefined, prev: undefined, next: undefined}
get backdrop() => this.getAttribute(backdrop) => null
componentDidMount setting customProps: ["backdrop"]
attributeChangedCallback {attr: "backdrop", prev: null, next: "foo"}
get backdrop() => this.getAttribute(backdrop) => foo
```

Resulting in the following DOM:

![image](https://user-images.githubusercontent.com/12807/65578091-6d558680-df75-11e9-8e52-fddc5502447f.png)

**Comment by simenbrekken** [comment]
Is [`componentDidMount` the right life-cycle method to synchronize props to attributes](https://github.com/nrkno/custom-element-to-react/blob/master/lib/index.js#L52)? If anything happens in `connectedCallback` that needs to read attributes they won't be available.

**Comment by toggu** [comment]
I'm seeing the same thing. CoreDialog keeps generating new <backdrop> elements even though I'm passing an id to a backdrop elements.

**Comment by toggu** [comment]
CoreDialog doesn't clean up these stray backdrop elements on unMount, causing the number of backdrop-elements to grow on each mount. This is a problem for single page apps.

**Comment by Maruz** [comment]
Not sure if it is the same problem, but the JSX version of core-dialog also does not handle boolean values to the backdrop prop: `TypeError: string.replace is not a function`
This is when I do `<CoreDialog backdrop={false} />`
Docs says it could be a strong or a boolean.
