### ISSUE TITLE
core-toggle: IE 11 error

### ISSUE THREAD

**Issue by laat** [nrkno/core-components#348]
```
TypeError: Ugyldig kallende objekt
    at Anonymous function (webpack:///node_modules/@nrk/core-toggle/core-toggle.cjs.js:170:6)
    at value (webpack:///node_modules/@nrk/core-toggle/core-toggle.cjs.js:298:8)
```
https://github.com/nrkno/core-components/blob/3355e8ed773a5adc9f037ebf0a14f42eb3faed6f/packages/utils.js#L54

`match.call` feiler.

Jeg får mange slike feil i produksjons-loggene, men tror ikke at det fører til problemer for bruker.

**Comment by htor** [comment]
thanks! this will be a good case for starting #345

**Comment by htor** [comment]
need some more context here. when does this error happen? i can reproduce the error by passing something that is not an element to `match.call(..)`.

**Comment by laat** [comment]
Jeg vet ikke hvordan man får fremprovosert feilen, det ligger bare i loggene i produksjon. 

Men hvis jeg skal gjette er det enten:

* `for (;el; el = el.parentElement)` som følger parent helt opp til document, uten å matche. `match.call(document, css)` tryner.

* eller klikk på svg: `document.querySelector('svg').dispatchEvent('click')`

**Comment by eirikbacker** [comment]
`el.parentElement` skal ikke gå til `document`, men er kanskje bug hos IE11 det ja :o

**Comment by laat** [comment]
tror det er click-event på svg egentlig. Når jeg trigger click på svg med dispatchEvent får jeg i hvertall feilen.

**Comment by eirikbacker** [comment]
og det er kun i testen. :)

**Comment by laat** [comment]
vi har fortsatt en del `svg>use#id` tags i knapper. dette skal på sikt bort.
https://github.com/jquery/jquery/issues/3877#issuecomment-349706832
https://github.com/mems/alexandrie-data/issues/9

**Comment by laat** [comment]
klarte å fremprovosere feilen i IE11.
![image](https://user-images.githubusercontent.com/146559/65961916-de0a1080-e457-11e9-93c4-256813ab862b.png)
ved klikk på direkte _ikonet_, kastes det feil på linjen.

**Comment by htor** [comment]
> tror det er click-event på svg egentlig. Når jeg trigger click på svg med dispatchEvent får jeg i hvertall feilen.

beklager, litt problemer med å "gjenskape" situasjonen her, har du noe kode til meg?
jeg får feilen ved å kalle `el.dispatchEvent('click')` i ie consollen, men det er uansett hvilket `el` det er snakk om.. ikke bare svg-er. virker som `dispatchEvent` er broken i ie. men så vidt jeg vet bruker vi vår egen patcha `dispatchEvent` (https://github.com/nrkno/core-components/blob/master/packages/utils.js#L66) ikke den innebygde. er det denne du tester med?

**Comment by laat** [comment]
Ja, jeg tror det er feil måte å teste det på.

tv.nrk.no har i noen få timer til en gammel header der jeg har verifisert feilen, noen ganger ved klikk på NRK TV logoen gir feilen.

**Comment by laat** [comment]
Tror dette er minimums eksempelet. Vi deployer ny header med nye ikoner i dag, som jeg tror ikke har feilen
```
<script async="" src="https://static.nrk.no/core-icons/3.1.1/core-icons.min.js" crossorigin="anonymous"></script>
<body>
  <svg>
    <use xlink:href="#nrk-logo-nrk-tv"></use>
  </svg>
  <... core toggle ett sted i DOM ...>
</body>
```

klikk på logo kaster feilen

**Comment by htor** [comment]
fikset i core-toggle@3.0.6
