### ISSUE TITLE
core-suggest: Input value changes by javascript wont update core-suggest

### ISSUE THREAD

**Issue by christianeide** [nrkno/core-components#366]
*Problem:* If you set the value of the input-field associated with core-suggest to empty, it will not trigger update of the dropdown or any other events.

Core-suggest adds eventlisteners to `click, input, keydown and focusin`. None of these events will pick up changes to inputfields set by javascript.

This leads to issues with the dropdown in a controled component that wont be reset after the inputfield is cleared. See gif.

![suggest_clean2](https://user-images.githubusercontent.com/15894115/67896450-c2ffee80-fb32-11e9-8fc1-c60e169b6022.gif)

*How to recreate:* 
1. https://static.nrk.no/core-components/latest/index.html?core-suggest/readme.md#example-ajax
2. Write fex the letter "e" in the country input-field
3. Observe a long list with elements
4. Deselect the input and see that the dropdown disapears
5. Open up console in dev tools and type in `document.getElementById('my-input-ajax').value = ''`
6. Observe that the inputfield is cleared
7. Focus the inputfield, observe that the dropdownlist still exists.

I would expect that the dropdown now should be empty.

Could perhaps mutationobservers be a solution for this?

**Comment by htor** [comment]
dette er uheldig.

vi kan ikke bruke mutation observer på `input.value`, siden den støtter ikke å watche idl-props, kun dom-attributter.. jeg undersøker om det kan være mulig å gjøre dette med:

```
    Object.defineProperty(this.input, 'value', {
      set: (val) => { 
        // gjør ting..
        return this.input.defaultValue = val
      },
      get: () => this.input.defaultValue
    })
```

**Comment by htor** [comment]
^se pr for mulig løsning

**Comment by htor** [comment]
støter på dette i safari 9:
```
Safari: "TypeError: Attempting to change the setter of an unconfigurable property."
```
tror dette er dead-end. ellers må vi gjøre en polling av input-value med `setTimeout`. dette kan bli treigt med mange suggest-elementer på siden

**Comment by eirikbacker** [comment]
mm, men et custom element kan vell bare overstyre en property? sånn som vi gjør med
```
set hidden function () { … }
get hidden function () { … }
```
kan kanskje gjøre samme for `.value` også passe på å trigge `change` og faktisk endre value med `setAttribute` eller `defaultValue`? :)

**Comment by htor** [comment]
det er snakk om `<input>`-elementet, ikke `<core-suggest`>, så dette vil ikke funke.

lukker denne, da det finnes ingen effektiv løsning som kan inkorporeres i core med dagens browser-støtte.
