### ISSUE TITLE
core-scroll: Support scrollable content that is center aligned

### ISSUE THREAD

**Issue by MKEshaswini** [nrkno/core-components#367]
- Make it possible to have scrollable content center aligned to begin with as shown in the following image. The circles in the image are called bubbles.

![Screenshot 2019-11-05 at 10 33 15](https://user-images.githubusercontent.com/17903388/68197679-ec010300-ffba-11e9-9b21-8a0da3935318.png)

- If the number of bubbles exceed the size of the container, we must get the scroll button to the right. PFA screenshot for reference:

![Screenshot 2019-11-05 at 10 59 18](https://user-images.githubusercontent.com/17903388/68197930-6762b480-ffbb-11e9-8c4b-a89d5e44dbb8.png)

- In mobile and iPad devices, the bubble are left aligned and scrollable.

![Screenshot 2019-11-05 at 11 02 34](https://user-images.githubusercontent.com/17903388/68198160-cde7d280-ffbb-11e9-98b3-37b3af07de1b.png)

**Comment by skjalgepalg** [comment]
This is achievable through CSS, I'll contact you directly
