### ISSUE TITLE
core-suggest: bruke egen matche-algoritme

### ISSUE THREAD

**Issue by htor** [nrkno/core-components#368]
det er ytret behov for å implementere fuzzy-søk med core-suggest. i dag bruker suggest en naiv algoritme som ikke funker bra som fuzzy søk, så kanskje det kan være fordelaktig å tilby en hook hvor konsument sender inn en funksjon som forteller suggest hva som er gyldige matcher?

noe a.l.a:
```js
const suggest = document.querySelector('core-suggest')
suggest.match = (thing) => { /* return useful thing*/ }
```

idéer til api er hjertelig velkomne!

**Comment by eirikbacker** [comment]
mm, dette kan du allerede gjøre? :)

```
const suggest = document.querySelector('core-suggest')
suggest.addEventListener('suggest.filter', (event) => {
  // event.target.children.forEach // Do the filter thingy here :)
})
```

**Comment by htor** [comment]
@gesi er denne eventen noe du kan bruke kanskje? jeg var litt kjapp til å foreslå en hook. men kanskje du ikke trenger det

**Comment by gesi** [comment]
Hadde faktisk ikke tenkt på at man kan bruke den eventen til å gjøre filtreringen. Et par tanker: 

1. Er `event.target.children` allerede prosessert av 'core-suggest` før denne fyrer?
2. I mitt tilfelle så brukte jeg `fuse.js` til å gjøre fuzzy-søk, og den søker i et array, og håndterer sortering. Hvis man skal bruke `sugges.filter`-eventen så må man håndtere dette selv, og man må også deale direkte med DOM-elementer og ikke sin egen datastruktur

Jeg brukte `core-suggest` mest fordi den gir meg UU og NRK-stiler ut av boksen, og det beste for meg hadde vært om jeg bare kunne skru av filtreringen med et attributt, og manipulere resultatene uavhengig av suggest.

Det jeg endte opp med å gjøre var å sette alle '[hidden]`-elementer til synlig, og fjerne `hidden`-attributtet så fort input endra seg

https://github.com/nrkno/dh-skatteliste-navnesok/blob/master/src/components/Search.svelte#L17-L55
