### ISSUE TITLE
core-suggest: matching funker rart in ie11

### ISSUE THREAD

**Issue by htor** [nrkno/core-components#373]
1. i ie11, gå til https://static.nrk.no/core-components/latest/index.html?core-suggest/readme.md
2. skriv inn 'e'
3. bare noen items matcher:

<img width="203" alt="Screenshot 2019-11-12 at 14 03 34" src="https://user-images.githubusercontent.com/1709263/68673980-40752700-0555-11ea-928e-fea94e67cd25.png">

4. backspace og skrive inn 'e' igjen og få annet resultat

**Comment by laat** [comment]
Ser ut som at det er forskjellig i MutationObserver oppførsel i IE11
