### ISSUE TITLE
core-suggest: auto-filling input should be optional?

### ISSUE THREAD

**Issue by astokke** [nrkno/core-components#385]
When selecting an item from core-suggest the input field is automatically populated with the value of the selected item. This might not be the wanted behaviour in all use cases. 

To avoid this happening I'm calling event.preventDefault() on the event, but I would prefer a flag in core-suggest allowing me to control if the input field is populated or not. 

Uploading screenshot of the search input after clicking the 'I nærheten' geolocation button in the suggest list. 

![image](https://user-images.githubusercontent.com/10544240/70141380-3a2b2400-1697-11ea-9b94-8fdff932ce1f.png)

**Comment by htor** [comment]
nettopp: å bruke `e.preventDefault` med `suggest.select` er måten å gjøre dette på. hva gjør at du ikke kan bruke denne eventen?
