### ISSUE TITLE
core-datepicker: Entire month disabled if month contains a disabled date with the same day of the month as the selected date

### ISSUE THREAD

**Issue by esseb** [nrkno/core-components#386]
Testcase: https://codesandbox.io/s/blue-pond-nz8z1

Relevant code from the testcase:
```js
const datePicker = document.querySelector("core-datepicker");

// Select a date in may 2019. Note that the day of the month is `06`
const selectedDate = new Date("2019-05-06");
datePicker.date = selectedDate;

// Disable a date in september 2019.
// Note that the day of the month is `06`, same as the selected date.
// `2019-09-07` for example does not cause the month to be disabled
// from the date dropdown.
const disabledDate = new Date("2019-09-06");
datePicker.disabled = date => {
  return date.valueOf() === disabledDate.valueOf();
};
```

**Comment by esseb** [comment]
Caused by the `disabled` callback being used both for determining if a month dropdown option should be disabled and to determine if a date button should be disabled.

The `disabled` callback, when called for each month dropdown option, receives a date object parameter with the day of that month and the day of the month equal to the selected date's day of the month.

I could fix this myself if the `disabled` callback let me know if is called in the context of a month or a date.

**Comment by esseb** [comment]
Originally discovered in a date picker where we simply disabled all dates after day using `(date) => date.valueOf() > today.valueOf()` which made it impossible to select the current month (December) in the month dropdown.

**Comment by laat** [comment]
I do not have the time to create a clean PR with tests, but I guess something like this could work

```js
function daysInMonth (dateInMonth) {
  const month = dateInMonth.getMonth()
  const date = new Date(dateInMonth)
  const days = []
  while (date.getMonth() === month) {
    days.push(new Date(date))
    date.setDate(date.getDate() + 1)
  }
  return days
}

function isMonthDisabled (dateInMonth, isDayDisabled) {
  return daysInMonth(dateInMonth).map(isDayDisabled).reduce((a, b) => a && b)
}
```

and changing
https://github.com/nrkno/core-components/blob/c4b5c679d08c9595e477799bd342108b2b86242a/packages/core-datepicker/core-datepicker.js#L158

```js
   option.disabled = isMonthDisabled(option.value, self.disabled)
```

**Comment by esseb** [comment]
@laat that looks like it should work.

In my project I've got this workaround for now (pseudo code-ish):
```js
// Create an options array up to the current month
const options = [
 // ...
  <option value="2019-10-d">,
  <option value="2019-11-d"
]

if (dayOfMonthOfCurrentlySelectedDate < dayOfMonthOfCurrentDate) {
  options.push(<option value="2019-12-d">
} else {
  // Set option value to current date
  options.push(<option value="2019-12-06">
}
```
