### ISSUE TITLE
core-dialog: getZIndex gir performance-problemer på sider med mange DOM-elementer

### ISSUE THREAD

**Issue by mortenkjelling** [nrkno/core-components#392]
Ser at `getZindex` looper gjennom alle DOM-noder og kjører  `Number(window.getComputedStyle(el).getPropertyValue('z-index')).` 
Dette er ganske performance-trøblete når man har en stor DOM. 

Kunne man introdusert et flagg som gjør at dette ikke skjer? På YR har vi god kontroll på z-index og bruker det bare i kontainere som har z-index=0, og har ei heller fremmed-elementer på siden med rare z-indexer, så vi trenger ikke være redd for at ting rendres over dialogene våre. 

Se eksempel her:
[klikk på datovelger eller en infoknapp](https://www.yr.no/nb/historikk/tabell/5-18700/Norge/Oslo/Oslo/Oslo%20(Blindern)?q=siste-13-m%C3%A5neder)

(Japp, abnormal stor DOM der ja)

**Comment by laat** [comment]
Kanskje vi skulle hatt attributt med ønsket zIndex? 

Hvis den er satt, så beregner vi den ikke automatisk.

**Comment by mortenkjelling** [comment]
Det gjør det kanskje litt mer anvendelig ja. God ide.

**Comment by esseb** [comment]
Vi har oversikt over z-indexer i vår SCSS-oppsett, så vi kunne også fint klart oss  med å sende inn `zIndex = false`

**Comment by eirikbacker** [comment]
eller bare kreve at zIndex settes av konsument? ha en default på typ 99 som lett overstyres av CSS, også kan core-dialog passe på kun rekkefølge av andre dialoger? :)

**Comment by htor** [comment]
så vi setter en default z-index i vår css (99?) og så lar vi konsument overstyre dette inline. virker ok. hva mener du når du sier passe på rekkefølge her? dette vil vel bli en major release også, siden det "brekker" auto z-index fra nå av?

**Comment by eirikbacker** [comment]
Hei! Sorry sent svar – tenker default 99 hos oss (ellerno slikt) er bra 👌
Passe på rekkefølge: `getZindex` kan, i stede for å hente zIndex fra _alle_ elementer, bare hente fra åpne core-dialogs. Så det blir mulig å åpne en dialog fra inni en dialog.
Eksempel:

```
<button for="dialog-1">
   First, the user clicks here
</button>
<core-dialog id="dialog-2">
   When dialog-2 opens, it will be behind dialog-1.
   Therefore we need getZindex, but only to ensure correct order of open dialogs.
</core-dialog>
<core-dialog id="dialog-1">
  <button for="dialog-2">
      Then, the user clicks here
   </button>
</core-dialog>
```

**Comment by htor** [comment]
fiks ut ute i siste patch. se nye docs:
https://static.nrk.no/core-components/latest/index.html?core-dialog/readme.md#stacking
