### ISSUE TITLE
migrére tester fra bstack til cbt

### ISSUE THREAD

**Issue by htor** [nrkno/core-components#397]
* fra https://www.browserstack.com/ til https://crossbrowsertesting.com/.
vi har ikke lenger bstack lisens, og har bestemt å bruke cbt.
* fjern`.disabled` fra github-action så testene kjører i ci

**Comment by aril-spetalen** [comment]
Det ser ut til at jeg har pirka borti dette for lenge siden: https://github.com/nrkno/core-components/tree/from-browserstack-to-cbt
Men jeg husker lite av hva dette var, og har heller ikke noe særlig innsikt i core-components. Så burde nok se på sammen med noen, om det skal bli Ok.
