### ISSUE TITLE
core-suggest: unexpected focus behaviour with VoiceOver and Chrome browser

### ISSUE THREAD

**Issue by astokke** [nrkno/core-components#410]
Steps to reproduce: 

1) Open https://static.nrk.no/core-components/latest/index.html?core-suggest/readme.md with Chrome on macOS with VoiceOver activated
2) Focus the input field in the example
3) Press down arrow on keyboard

**Expected behaviour:** 
First item in list gets focus

**Actual behaviour:** 
Input field gets focus. 

Pressing the down arrow after focusing the input field (when VoiceOver is activated) seems to fire two `focusin` events in a row. The first one it sets focus to the first item in the suggest component, but in the second event it sets focus back to the input field. 
After this it seems to have normal behaviour, and you can navigate as excepted with the keyboard.

**Comment by eirikbacker** [comment]
This is no longer a issue in Chrome on MacOS - tested and verified by @kristofferlium 🎉
