### ISSUE TITLE
core-scroll: scroll('right') is undefined when having all items wrapped are in a element

### ISSUE THREAD

**Issue by ssaegrov** [nrkno/core-components#418]
We are trying to use core-scroll for a horisontal list of elements. To improve accessibility we want to use core-scroll as follows:
`<CoreScroll className="my-scroll" onScrollChange={this.onScroll}>
    <ul>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
    </ul>
</CoreScroll>`

We utilize target.scroll('left') and target.scroll('right') on our scroll buttons, however scroll.right('right') is undefined when using core-scroll as above. If we remove the `<ul>` element everything works fine.

**Comment by htor** [comment]
hva mener du med `scroll.right(..)` er undefined? 
uansett, må du bruke `items`-attributten hvis du skal bruke `<ul>`: 
https://static.nrk.no/core-components/latest/index.html?core-scroll/readme.md#example-custom-child-items

**Comment by ssaegrov** [comment]
Her leste jeg dokumentasjonen for dårlig, min feil! Lukker saken :)
