### ISSUE TITLE
core:Tabs e.preventDefault() not working in IE

### ISSUE THREAD

**Issue by christianeide** [nrkno/core-components#44]
e.preventDefault is not working in IE on Windows to prevent tabToggle. Works in Opera and Chrome on Mac and Windows. 

Also tried variants of the following code without any luck (From this thread https://stackoverflow.com/questions/1000597/event-preventdefault-function-not-working-in-ie):  
e.preventDefault ? e.preventDefault() : (event.returnValue = false)

Is this missing functionality in core:tabs, or is this a general issue?

**Comment by eirikbacker** [comment]
Well spotted @christianeide! Bug-fix applied to all components: https://github.com/nrkno/core-components/releases/tag/v1.3.7
