### ISSUE TITLE
core-dialog: both dialog and backdrop gets z-index: 0 and fails to show above content

### ISSUE THREAD

**Issue by eriksalhus** [nrkno/core-components#454]
Looks like core-dialog is not working properly in Safari 12. Seems as though both elements gets `z-index: 0`. 

> let zIndex = window.getComputedStyle(this).getPropertyValue('z-index')
> if (zIndex === 'auto' && this.style.zIndex === '') { // Place this dialog over uppermost dialog if not controlled in CSS or JS
- https://github.com/nrkno/core-components/blob/master/packages/core-dialog/core-dialog.js#L42

Since `zIndex` is `0`, my guess is that core-dialog should not update the z-index because it is set, and not to `auto`. 
Makes sense, but maybe it also makes sense to check if `zIndex === '0'`?

Caused by #445

**Comment by eriksalhus** [comment]
@htor Did you test core-dialog v3.0.6 on Safari 12? Looks like Safari 12 reports `0` when no z-index is set.

**Comment by htor** [comment]
takk for denne .
vi burde sjekke `zIndex === '0'. lager en pr på dette
