### ISSUE TITLE
core-scroll: `for` is not a valid HTML5 `<button>` attribute

### ISSUE THREAD

**Issue by simenbrekken** [nrkno/core-components#463]
While implementing `core-scroll` in an application I ran into an issue where using the JSX version of `core-scroll` didn't allow me to define `<button htmlFor="my-core-scroll-id">`. This is due to [for only being a valid attribute for `<label>`](https://html.spec.whatwg.org/#the-label-element).

A possible non-breaking change is improving `core-scroll`'s [button selector](https://github.com/nrkno/core-components/blob/master/packages/core-scroll/core-scroll.js#L62) by adding something like this:

```js
const btn = this.id && closest(event.target, `[for="${this.id}"], [data-for="${this.id}"]`)
```

I've made a sandbox showcasing the improvement here: https://codesandbox.io/s/core-scroll-buttons-xfq93

**Comment by piofinn** [comment]
This is also the case in `core-toggle`.
