### ISSUE TITLE
core-scroll: issues with target.scrollLeft and target.scrollRight when zoomed in

### ISSUE THREAD

**Issue by AElmoznino** [nrkno/core-components#464]
Hey! Great library, we've started using it now at [urplay.se](https://www.urplay.se) and we're happy about it! 😄 

Trying my best to describe this issue.

Abbreviated code example:
```
const SideScroll = () => {
  const [scroll, setScroll] = useState(null)

  const onScroll = ({ target }) => {
    setScroll({
      left: target.scrollLeft ? () => target.scroll('left') : null,
      right: target.scrollRight ? () => target.scroll('right') : null,
    })
  }

  return (
      <CoreScroll onScrollChange={element => onScroll(element)}>
        /** contents **/
      </CoreScroll>
      <button disabled={!scroll?.right} onClick={scroll?.right}>
        <ArrowRight />
      </button>
   ) 
```

The issue it that scroll.right isn't set correctly when I'm not at 100% zoom level, meaning that the Right button shows even when there are no more results to show.
I've tried console.logging target.scrollRight within onScroll. It logs as `0` when zoomed to 100% or larger, but at certain levels below 90% it logs to `-1` (meaning that the right arrow starts appearing).

Browser: Chrome 81

**Comment by skjalgepalg** [comment]
A fix for this has been released in @nrk/core-scroll@4.2.1 ([core-components release 9.1.1](https://github.com/nrkno/core-components/releases/tag/v9.1.1)).
