### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by laat** [nrkno/core-components#50]
`npm test` on master is currently broken. Travis or similar is awesome to avoid this state. 😄

**Comment by wwalmnes** [comment]
An alternative would be to have a commit hook which runs `npm test`. It won't allow the commit unless the tests pass. Would be the shortest path with the least amount of setup and might be enough for our use case. But Travis would be nice too 😄 . @eirikbacker what do you think?

**Comment by laat** [comment]
pre-commit hooks is in my opinion not sufficient, they are easy to avoid and it is not always easy to make them work cross-platform and cross-dev-pc.

Adding a .travis.yaml to a open source github repo is trivial.

with sufficiently slow/annoying pre-commit hooks I alias `git commit` to `git commit --no-verify` 😇

**Comment by wwalmnes** [comment]
True. I forgot for a moment that this repo is open source so we don't need a payment plan. I am now fully behind your request of adding Travis (or something similar) 💪 !

> with sufficiently slow/annoying pre-commit hooks I alias git commit to git commit --no-verify

Haha 😄

**Comment by eirikbacker** [comment]
@laat @wwalmnes have any of you done this - I'd very much like it, but would be nice if you have experience to get help the first time :)
