### ISSUE TITLE
core-dialog: Prevent background scrolling when open option

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-components#616]
As a user I want, html/body scrolling to stop when dialog is open - can this be an option core-dialog fixes for me?

**Comment by skjalgepalg** [comment]
Overscroll-behavior sounds like it should solve this for most cases.

https://caniuse.com/?search=overscroll-behavior
- Mind that it's only available as opt-in under experimental features in safari and safari on iOS with no apparent polyfill or workaround short of temporarily modding body styles.

**Comment by eirikbacker** [comment]
@skjalgepalg jupp :) maybe mention it in the docs as this is quite a new feature and our users might not be aware of it? as overscroll-behavior is nice to have and not a must, I do not see safari not supporting it (yet) as a blocker :)
