### ISSUE TITLE
webdriver hinders local development

### ISSUE THREAD

**Issue by skjalgepalg** [nrkno/core-components#637]
Current `postinstall` script blocks running `npm install` for some developers.

Short term alternatives:
* Global install `webdriver-manager` (dubious fix)
* Remove `postinstall` script
* 

Longer term:
* Migrate away from `protractor` for local testing.
  * Use `jest` or similar framework
* Setup remote tests using whichever framework is chosen in above task
* While at it, look into running tests for React components also

**Comment by htor** [comment]
Hi!

I think at the time it was decided to use protractor because jsdom (used by some other testing frameworks) did not support custom elements. That might have changed, but I'm not sure :-)

**Comment by skjalgepalg** [comment]
Solved by moving to Playwright under #717
