### ISSUE TITLE
Typeerror i core-suggest 

### ISSUE THREAD

**Issue by TatyanaLo** [nrkno/core-components#658]
Ved bruk av core-suggest v. 1.3.3.
![Screenshot 2022-09-15 at 16 25 49](https://user-images.githubusercontent.com/16648390/190429909-a6b8e360-bd1a-4fed-b9c2-a157e9bc4b0b.png)

**Comment by TatyanaLo** [comment]
![Screenshot 2022-09-15 at 16 31 14](https://user-images.githubusercontent.com/16648390/190431175-734ef153-b33d-433b-be2a-58fbce50a56b.png)

**Comment by skjalgepalg** [comment]
Hi, thanks for the heads-up!
Could you provide an example of your implementation so I can reproduce this?

**Comment by TatyanaLo** [comment]
søker helt fint mens man skriver, men etter at man har valgt fra listen blir value undefined. 

<Input
        label="Finn problemstilling"
        defaultValue={value?.display || ""}
        onChange={updateInput}
        list="id"
      />`
<CoreSuggest
        id="id"
        highlight="off"
        onSuggestSelect={(event: CustomEvent<HTMLElement>) => {
          const value = event.detail.getAttribute("data-value");
          const coding = codingList.find((coding) => coding.code === value);
          onChange(coding);
        }}
      >
        {codingList.length > 0 ? (
          <ul className="kj-careplan-condition-search__list">
            {codingList.map((coding) => (
              <li key={coding.code}>
                <button data-value={coding.code}>{capitalize(coding?.display) || coding.code}</button>
              </li>
            ))}
          </ul>
        ) : null}`

**Comment by skjalgepalg** [comment]
@TatyanaLo could you please verify if the problem persists in version @nrk/core-suggest@1.3.4-0?

`npm i -E @nrk/core-suggest@1.3.4-0`

**Comment by TatyanaLo** [comment]
Fixed!

**Comment by skjalgepalg** [comment]
Merged fix and published patch @nrk/core-suggest@1.3.4 to npm from master
