### ISSUE TITLE
core-scroll: hiding scrollbars osx with touchpad/magic mouse

### ISSUE THREAD

**Issue by laat** [nrkno/core-components#73]
Hvordan kan jeg skjule denne scroll baren her:

![skjermbilde 2018-07-12 kl 14 37 08](https://user-images.githubusercontent.com/146559/42633720-9d31cc5e-85e1-11e8-8fc4-105ddf22c6a1.png)

Hvis pekeren er over scroll baren når jeg scroller får jeg dette:
![screen shot 2018-07-12 at 14 43 15](https://user-images.githubusercontent.com/146559/42633870-fcc088a4-85e1-11e8-838d-0a843576b7f6.png)

**Comment by eirikbacker** [comment]
Well, it is pr. definition not possible to calculate the height of the scrollbar in OSX when the "auto hide" system setting is on. We can of course guess it is roughly 20px (all browsers are 20 or less) and do a minus margin, but as the scrollbar is only visible during scroll (like the mobile convention) we have for now just concluded to let it appear during movement :)

**Comment by laat** [comment]
Utfordringen jeg har her: 
![screen shot 2018-07-12 at 14 43 15](https://user-images.githubusercontent.com/146559/42633870-fcc088a4-85e1-11e8-838d-0a843576b7f6.png)

er at scrollbaren ikke forsvinner av seg selv når den først har havnet i den staten. Og da er det for mitt tilfelle kanskje bedre om jeg hadde gjort -20px trikset

**Comment by laat** [comment]
Det kan testes på https://tv.nrk.no/serie/dyrevenn

**Comment by laat** [comment]
Kult! takker! 👍
