### ISSUE TITLE
Add types declaration file to npm package

### ISSUE THREAD

**Issue by Celsiusss** [nrkno/core-components#758]
I am using core-scroll in a React project with Typescript. The package does not have an associated Typescript declarations file, but type declarations do exist in the project.

Not sure on how the build and publishing process is, but consider adding a `types` entry to the `package.json` of the projects, as documented [here](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

**Comment by skjalgepalg** [comment]
NRK is no longer actively maintaining and developing Core-components. 

We recommend looking into [u-elements](https://u-elements.github.io/u-elements/) as a possible replacement.
