### ISSUE TITLE
Support tagging functionality in core-input / core-tags

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/core-components#9]
Branch started here https://github.com/nrkno/core-components/tree/feature/core-tags

**Comment by htor** [comment]
this would be nice to have in kaleido-picker in the metadata editor. for instance the "Emneknagger" field.

**Comment by eirikbacker** [comment]
New branch started https://github.com/nrkno/core-components/tree/feature/core-input-tags

**Comment by skjalgepalg** [comment]
This feature is possibly stale and requires further research to establish requirements for present state of core-scroll and web/browser landscape. We need to look into speccing this further. Suggestions and input on this topic are, as always, most welcome
